### ISSUE TITLE
Stack overflow when analysing javascript

### ISSUE THREAD

**Issue by lukeapage** [SonarSource/SonarJS#1276]
**I want to report a bug.**

**SonarJS version:** 5.0.0.6962<br>
**SonarQube version:** 7.6<br>

When running the analysis on my codebase I get an stack overflow in the sonar qube java. I will attach logs (they are too big to be included inline)

I am fairly sure it is not caused by the filename logged just before the exception. How do I work out what file does cause the issue?

**Comment by lukeapage** [comment]
[sonar-logs.txt](https://github.com/SonarSource/SonarJS/files/3468842/sonar-logs.txt)

**Comment by lukeapage** [comment]
If you can provide some information on how to enable enough debugging to see what file is being parsed so I can try disabling bits of the file, I can try and narrow it down a bit further.

**Comment by lukeapage** [comment]
I've located the file that causes the problem and I can send it to SonarQube to help you fix this issue, but I do not want to post the file publicly. Its not obvious from the file what is wrong.

**Comment by andrea-guarino-sonarsource** [comment]
hi @lukeapage , 
thank you for your investigation. From the logs it looks like it's something related to symbolic execution.

> If you can provide some information on how to enable enough debugging

That's possible by running `sonar-scanner` with `-X` option.

> I've located the file that causes the problem and I can send it to SonarQube to help you fix this issue, but I do not want to post the file publicly. Its not obvious from the file what is wrong.

I'm not aware of a way of sending PMs on Github.
However, I'd suggest to open a thread about this bug in our [community forum](https://community.sonarsource.com/). There you can send privately to me by PM your file causing the issue.

**Comment by lukeapage** [comment]
done
https://community.sonarsource.com/t/stack-overflow-when-analysing-javascript/12831

Should I be raising bugs in guthub or on the community site?

**Comment by andrea-guarino-sonarsource** [comment]
Thanks!
For SonarJS bug reports you can continue using GitHub.

**Comment by robatwilliams** [comment]
Still an issue with Version 8.3.1 (build 34397)

Any update on solving this issue, or what it is about our file that causes it?

**Comment by vilchik-elena** [comment]
@robatwilliams we plan to drop this part of analyzer this year, so it's not worth investigating and fixing the root cause. You can try to find the file causing the the problem and temporarily exclude it from analysis (enable debug logs and check what is the file logged just before the failure). Sorry for the inconvenience!

**Comment by vilchik-elena** [comment]
closing as parser is removed
